# Generated by Django 3.2.8 on 2021-10-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageWABot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=15)),
                ('from_phone', models.CharField(max_length=15)),
                ('to_phone', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=500)),
                ('request_at', models.DateTimeField()),
            ],
        ),
    ]
